subprojects {
    apply plugin: 'java-library'
    apply plugin: 'maven-publish'

    group = project.maven_group
    version = project.mod_version

    tasks.withType(JavaCompile).configureEach {
        options.encoding = "UTF-8"
        options.release.set(21)
    }
}

allprojects {
    configurations.all {
        resolutionStrategy {
            failOnVersionConflict()
        }
    }
}