# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Java version
java_version=21

# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=com.rigorberto
archives_base_name=ZstdNetworkProject

# Dependencies
neoforge_version=21.1.248
paper_version=1.21.1-R0.1-SNAPSHOT
velocity_version=3.5.1