plugins {
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.github.luben:zstd-jni:${project.zstd_version}"
    compileOnly "io.netty:netty-all:${project.netty_version}"
}

jar {
    manifest {
        attributes(
            'Automatic-Module-Name': 'com.rigorberto.zstdnetworkproject.common'
        )
    }
}
