plugins {
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.github.luben:zstd-jni:${project.zstd_version}"
    compileOnly "io.netty:netty-all:4.2.18.Final"
    compileOnly "org.slf4j:slf4j-api:${project.slf4j_version}"

    testImplementation "io.netty:netty-all:4.2.18.Final"
    testImplementation "org.junit.jupiter:junit-jupiter:5.11.0"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes(
            'Automatic-Module-Name': 'com.rigorberto.zstdnetworkproject.common'
        )
    }
}
