plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version "${moddev_version}"
}

repositories {
    mavenCentral()
}

neoForge {
    version = project.neoforge_version

    mods {
        "zstdnetworkproject" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation project(':common')
    implementation "com.github.luben:zstd-jni:${project.zstd_version}"
}

jar {
    dependsOn project(':common').jar
    manifest {
        attributes(
            'Mod-Container': 'com.rigorberto.zstdnetworkproject.neoforge.ZstdNetworkProjectNeoForge',
            'Mod-Version': project.version
        )
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from('src/main/resources') {
        include 'META-INF/neoforge.mods.toml'
    }
    from {
        zipTree(project(':common').jar.archiveFile.get()).matching { include 'com/rigorberto/zstdnetworkproject/**' }
    }
    from {
        def zstd = configurations.runtimeClasspath.find { it.name == "zstd-jni-${project.zstd_version}.jar" }
        zstd ? zipTree(zstd).matching { exclude 'META-INF/MANIFEST.MF' } : project.files()
    }
}
