plugins {
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenCentral()
    maven { url = "https://repo.papermc.io/repository/maven-public/" }
}

dependencies {
    implementation project(':common')
    implementation "com.github.luben:zstd-jni:${project.zstd_version}"
    compileOnly "io.netty:netty-all:${project.netty_version}"
    compileOnly "io.papermc.paper:paper-api:${project.paper_version}"
    runtimeOnly "io.papermc.paper:paper-api:${project.paper_version}"
}

jar {
    dependsOn project(':common').jar
    manifest {
        attributes(
            'Main-Class': 'com.rigorberto.zstdnetworkproject.paper.ZstdNetworkProjectPaper',
            'Plugin-Version': project.version
        )
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from('src/main/resources') {
        include 'plugin.yml'
    }
    from {
        zipTree(project(':common').jar.archiveFile.get()).matching { include 'com/rigorberto/zstdnetworkproject/**' }
    }
    from {
        def zstd = configurations.runtimeClasspath.find { it.name == "zstd-jni-${project.zstd_version}.jar" }
        zstd ? zipTree(zstd).matching { exclude 'META-INF/MANIFEST.MF' } : project.files()
    }
}
