name: ZstdNetworkProject
version: ${version}
main: com.rigorberto.zstdnetworkproject.paper.ZstdNetworkProjectPaper
api-version: 1.21
author: Rigorberto
description: Zstd packet compressor for Minecraft Paper server